#pragma config(Motor,  port2,           leftmotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,          rightmotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
    while (1==1){
        // 0 for min speed, 127 for max speed
        motor[leftmotor] = 127;
        motor[rightmotor] = -127;
    }
}
