#pragma config(Sensor, in1,    distanceSensor, sensorAnalog)
#pragma config(Sensor, dgtl3,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl6,  ,               sensorRotation)
#pragma config(Sensor, dgtl12, lineSensor,     sensorDigitalIn)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           grabMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int speed;            // Will hold a speed for the motors.
	int sonar_value;      // Will hold the current reading of the sonar sensor.
	int distance = 5;    // Specified distance to be at 5 centimeters.

	while (1==1) {
		//brain.Screen.print(SensorValue [sonarSensor]);

		if (SensorValue [lineSensor] == 1) {
			motor [rightMotor] = -30;
			motor [leftMotor] = 30;
			wait1Msec (200);
		} else {
				motor [leftMotor] = 0;
				motor [rightMotor] = 0;
		}
	}

}
