const short DEFAULT_MOTOR_DRIVING_SPEED = 60;
const short SLOW_MOTOR_DRIVING_SPEED = 40;
const short DEFAULT_MOTOR_TURNING_SPEED = 60;
const short DEFAULT_BALL_MOTOR_SPEED = 127;
const short MS_PER_DEGREE = 8;

const short START_MOVE_FIELD_TIME = 2000;
const short END_MOVE_FIELD_TIME = 1000;
const short BALL_OUT_MOTOR_SLEEP_TIME = 2000;

const short ROBOT_REAR_DISTANCE_THRESHOLD = 10;
const short ROBOT_FRONT_DISTANCE_THRESHOLD = 10;
const short ROBOT_BALL_DISTANCE_THRESHOLD = 60;
const short ROBOT_BALL_SHORT_DISTANCE_THRESHOLD = 15;
const short ROBOT_SENSOR_DIFF_THRESHOLD = 5;

const short ROBOT_STATE_CORRECT_VALUE = 3;
