#pragma config(Sensor, in1,    dist_long0,     sensorAnalog)
#pragma config(Sensor, in2,    dist_long1,     sensorAnalog)
#pragma config(Sensor, in3,    dist_long2,     sensorAnalog)
#pragma config(Sensor, in5,    on_switch,      sensorAnalog)
#pragma config(Sensor, dgtl1,  compass_west,   sensorDigitalIn)
#pragma config(Sensor, dgtl2,  compass_south,  sensorDigitalIn)
#pragma config(Sensor, dgtl3,  compass_east,   sensorDigitalIn)
#pragma config(Sensor, dgtl4,  compass_north,  sensorDigitalIn)
#pragma config(Sensor, dgtl6,  line_FL,        sensorDigitalIn)
#pragma config(Sensor, dgtl7,  line_FR,        sensorDigitalIn)
#pragma config(Sensor, dgtl8,  line_BL,        sensorDigitalIn)
#pragma config(Sensor, dgtl9,  line_BR,        sensorDigitalIn)
#pragma config(Sensor, dgtl10, ball_switch,    sensorTouch)
#pragma config(Sensor, dgtl11, bumper_L,       sensorTouch)
#pragma config(Sensor, dgtl12, bumper_R,       sensorTouch)
#pragma config(Motor,  port2,           left_motor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ball_out_motor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           ball_in_motor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           right_motor,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
line sensor
- 4 corners of robot

distance Sensors
- ball detection (ball diameter 6.5cm)
- detect robot (on top)
- if ball collected [short 4-30cm]
- one at back to know distance gg back (must be sufficiently high up)

- 2Y0A21 F 6Z * 2 (10 to 80cm)
- 2Y0A21 F 09 * 1 (10 to 80cm)
- 0A41SK * 1 (4 to 30cm)

10 to 20cm

Motors (10)
- driver * 2
- ball_in * 1
- ball_out * 1

Digital inputs (12)
- line * 4
- limit switch * 2 for bumper, * 1 for ball switch, total 3
- compass * 4

Analog inputs (8)
- dist * 3
- * 1 for on-off
*/
short ball_count = 0; //number of balls collected by robot
char start_position;

#include "compass.c"
#include "distance_sensors.c"
#include "line_sensors.c"
#include "movement.c"
#include "robot_state.c"

short cycles = 0; // detect number of times on-off switch was pressed while robot is on

short test;
byte left;
byte right;
byte front;
byte back;

void wait_for_on();

task full_stop();
task detection();
task action();

//-----------end of global functions/tasks-----------

task action() {
	while (true) {
		robot_state_machine();

		//add in all possible combinations of sensor values and robot state values to determine corresponding robot action
		switch(robot_state) {
			case START:
				switch (start_position) { //robot turn on spot until detect ball which will cause state change
					case 'L':
						turn(1, 30);
						break;
					case 'R':
						turn(-1, 30);
						break;
				}
			case BALL_DETECTED:
				drive(1, 30);
				if (distance_long1 < 20 && SensorValue [ball_switch] == 0 && distance_long0 > 20) {
					collect_ball();
				}
				break;
			case HOME:
				stop_movement();
				deposit_ball();
				ball_count++;
				move_field();
				break;
			case BALL_COLLECTED_NO_ROBOT:
				motor [ball_in_motor] = 0;
				//add code to change state to return to base
				break;

				default:
					stop_movement();
		}

	}
}

task detection() {
	while (true) {
		distance_calculator();
		sleep(50);

		get_direction();

		left = !SensorValue[line_FL] << 0;
	 	right = !SensorValue[line_FR] << 1;
		front = !SensorValue[line_BL] << 2;
		back = !SensorValue[line_BR] << 3;
		test = back | front | left | right;
		react_to_sensors(test);
	}
}

task full_stop() { // stop all tasks and movements except for emergency_stop and main
	while (SensorValue [on_switch] == 0) {/* Nothing is executed when limit switch isn't pressed to off robot */}

	stopTask(detection);
	stopTask(action);
	stop_movement();
	motor [ball_in_motor] = 0;
	motor [ball_out_motor] = 0;

	wait_for_on();
}

void wait_for_on() {
	while (SensorValue [on_switch] == 0) {/* Nothing is executed when limit switch isn't pressed */}
	clearTimer(T1);
	while (SensorValue [on_switch] == 1) {/* Nothing executed when limit switch isn't released */}
	if (time1[T1] < 2000) {start_position = 'L';} // robot start on left position when on switch just touch and go
	else {start_position = 'R';} // robot start on right position when on switch held for at least 2s

	if (cycles == 1) {
		clearTimer(T1);
		move_field(); //move field only if robot did not start again
	}
	startTask(detection);
	startTask(action);
	clearTimer(T2);
	cycles++;

	startTask(full_stop);
}

task main() {
	wait_for_on();
	while (true) {/* Loop ensures that main task is not terminated */}
}
