#pragma config(Sensor, in2,    dist_long1,     sensorAnalog)
#pragma config(Sensor, in3,    dist_long2,     sensorAnalog)
#pragma config(Sensor, in8,    dist_long0,     sensorAnalog)
#pragma config(Sensor, dgtl1,  compass_west,   sensorDigitalIn)
#pragma config(Sensor, dgtl2,  compass_south,  sensorDigitalIn)
#pragma config(Sensor, dgtl3,  compass_east,   sensorDigitalIn)
#pragma config(Sensor, dgtl4,  compass_north,  sensorDigitalIn)
#pragma config(Sensor, dgtl5,  on_switch,      sensorTouch)
#pragma config(Sensor, dgtl6,  line_FL,        sensorDigitalIn)
#pragma config(Sensor, dgtl7,  line_FR,        sensorDigitalIn)
#pragma config(Sensor, dgtl8,  line_BL,        sensorDigitalIn)
#pragma config(Sensor, dgtl9,  line_BR,        sensorDigitalIn)
#pragma config(Sensor, dgtl10, ball_switch,    sensorTouch)
#pragma config(Sensor, dgtl11, bumper_L,       sensorTouch)
#pragma config(Sensor, dgtl12, bumper_R,       sensorTouch)
#pragma config(Motor,  port2,           left_motor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ball_out_motor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           ball_in_motor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           right_motor,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
distance Sensors
- ball detection (ball diameter 6.5cm)
- detect robot (on top)
- if ball collected [short 4-30cm]
- one at back to know distance gg back (must be sufficiently high up)

- 2Y0A21 F 6Z * 2 (10 to 80cm)
- 2Y0A21 F 09 * 1 (10 to 80cm)
- 0A41SK * 1 (4 to 30cm)

10 to 20cm

Motors (10)
- driver * 2
- ball_in * 1
- ball_out * 1

Digital inputs (12)
- line * 4
- limit switch * 2 for bumper, * 1 for ball switch, total 3
- compass * 4

Analog inputs (8)
- dist * 3
- * 1 for on-off
*/
short cycles = 0; // detect number of times on-off switch was pressed while robot is on
short ball_count = 0; //number of balls collected by robot
char start_position;

//debugging variables
bool is_turning = false;
bool is_moving_after_first_ball = false;

#include "compass.c"
#include "movement.c"
#include "distance_sensors.c"
#include "line_sensors.c"
#include "robot_state.c"
#include "scanning.c"

void wait_for_on();
task full_stop();
task detection();
task action();

//-----------end of global functions/tasks-----------

task action() {
	while (true) {
		robot_state_machine();

		//add in all possible combinations of sensor values and robot state values to determine corresponding robot action
		switch(robot_state) {
			case START:
				switch (start_position) { //robot turn on spot until detect ball which will cause state change
					case 'L':
						turn(1, 30);
						break;
					case 'R':
						turn(-1, 30);
						break;
				}
				break;

			case BALL_DETECTED: //drive towards ball, start spinning ball_in_motor when close enough to ball
				drive(1, 60);
				if (distance_ball_front < 20 && SensorValue [ball_switch] == 0 && distance_robot_front > distance_ball_front + 5) {
					collect_ball();
				}
				break;

			case HOME: //both bumper switches pressed, ball in robot and not back robot means deposit ball
				stop_movement();
				deposit_ball();
				ball_count++;
				is_moving_after_first_ball = true;
				move_field();
				is_moving_after_first_ball = false;
				break;

			case BALL_COLLECTED_NO_ROBOT: //robot collected ball and no nearby robots
				motor [ball_in_motor] = 0;
				stop_movement();
				is_turning = true;
				turn_to_north();
				is_turning = false;
				drive(-1, 127);
				break;

			case ROBOT_FRONT_DETECTED_BALL_IN: //robot collected ball but robot in front, reverse away first
				motor [ball_in_motor] = 0;
				drive(-1, 60);
				break;

			case ROBOT_FRONT_DETECTED_BALL_OUT: //to be determined
				//add code
				break;

			case ROBOT_REAR_DETECTED_BALL_IN: //robot collected ball but robot behind, move foward first and maneuver somewhere else??
				motor [ball_in_motor] = 0;
				drive(1, 60);
				//add code to maneuver away?
				break;

			case ROBOT_REAR_DETECTED_BALL_OUT: //to be determined
				//add code
				break;

			case BALL_SEARCH_NO_ROBOT:
				ball_scanning();
				break;

			case LINE_SENSOR_DETECTED:
				react_to_line_sensors();
				break;

			default:
				stop_movement();
				break;
		}

	}
}

task detection() {
	while (true) {
		distance_calculator();
		get_direction();
		get_line_sensor_state();
	}
}

task full_stop() { // stop all tasks and movements except for emergency_stop and main
	while (SensorValue [on_switch] == 0) {/* Nothing is executed when limit switch isn't pressed to off robot */}

	stopTask(detection);
	stopTask(action);
	stop_movement();
	motor [ball_in_motor] = 0;
	motor [ball_out_motor] = 0;
	sleep(2000);
	wait_for_on();
}

void wait_for_on() {
	while (SensorValue [on_switch] == 0) {/* Nothing is executed when limit switch isn't pressed */}
	clearTimer(T1);
	while (SensorValue [on_switch] == 1) {sleep(100);}
	cycles++;
	if (cycles == 1) {
		if (time1[T1] < 2000) {start_position = 'L';} // robot start on left position when on switch just touch and go
		else {start_position = 'R';} // robot start on right position when on switch held for at least 2s
		clearTimer(T1);
		move_field(); //move field only if robot did not start again
	}
	startTask(detection);
	startTask(action);
	startTask(full_stop);
}

task main() {
	wait_for_on();
	while (true) {/* Loop ensures that main task is not terminated */}
}
