#pragma config(Sensor, in1,    fb_back_left,   sensorAnalog)
#pragma config(Sensor, in2,    fb_back_right,  sensorAnalog)
#pragma config(Sensor, in3,    fb_front_right, sensorAnalog)
#pragma config(Sensor, in4,    fb_front_left,  sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

short first_ball_no = 0;

void get_first_ball() {
	while (true) {
		if (SensorValue [fb_back_left] > 0) {
			first_ball_no = 1;
			break;
		}
		else if (SensorValue [fb_back_right] > 0) {
			first_ball_no = 2;
			break;
		}
		else if (SensorValue [fb_front_right] > 0) {
			first_ball_no = 3;
			break;
		}
		else if (SensorValue [fb_front_left] > 0) {
			first_ball_no = 4;
			break;
		}
	}
}

task main() {
	get_first_ball();
	while (true) {}
}
