#pragma config(Sensor, in1,    dist_long0,     sensorAnalog)
#pragma config(Sensor, in2,    dist_long1,     sensorAnalog)
#pragma config(Sensor, in3,    dist_long2,     sensorAnalog)
#pragma config(Sensor, in4,    dist_short,     sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float voltage_long0;
float voltage_long1;
float voltage_long2;
float voltage_short;

float distance_long0;
float distance_long1;
float distance_long2;
float distance_short;

const string robotStateNames[5] = {
    "ROBOT_FRONT_DETECTED",
    "BALL_DETECTED",
    "ROBOOT_REAR_DETECTED",
    "BALL_COLLECTED",
    "BLANK"
};

enum robotState {
    ROBOT_FRONT_DETECTED,
    BALL_DETECTED,
    ROBOT_REAR_DETECTED,
    BALL_COLLECTED,
    BLANK,
};
robotState robot_state = BLANK;

// only after 5 counts, then declare that the state is correct; this is to correct the random surges
robotState detected_state = BLANK;
robotState previous_detected_state = BLANK;
int state_counter = 0;

void distance_calculator() {
	voltage_long0 = (SensorValue [dist_long0]) * (5.0 / 4096.0);
	voltage_long1 = (SensorValue [dist_long1]) * (5.0 / 4096.0);
	voltage_long2 = (SensorValue [dist_long2]) * (5.0 / 4096.0);
	voltage_short = (SensorValue [dist_short]) * (5.0 / 4096.0);

	distance_long0 = 27.534 * pow(voltage_long0 , -1.207);
	distance_long1 = 27.534 * pow(voltage_long1 , -1.207);
	distance_long2 = 27.534 * pow(voltage_long2 , -1.207);
	distance_short = pow(2.7818281828, 2.507) * pow(voltage_short , -1.123);

	if (distance_short > 40) {
		distance_short = 40;
	}
}


task main()
{

while (true) {distance_calculator();}

}
