#pragma config(Sensor, dgtl9,  lineSensorLeftFront, sensorDigitalIn)
#pragma config(Sensor, dgtl10, lineSensorLeftBack, sensorDigitalIn)
#pragma config(Sensor, dgtl11, lineSensorRightFront, sensorDigitalIn)
#pragma config(Sensor, dgtl12, lineSensorRightBack, sensorDigitalIn)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           grabMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//maybe set sth like after long time of no change in state, robot does sth to break out of stale??

int detectBoundary() { //sensor value is 1 if detect? must test to be sure
	/*
	no corners - move as per normal
	left front corner - turn right by x degrees, move as per normal
	left back corner - (if was moving backward, move forward a bit, turn left, move as per normal) (otherwise, it can only hit it during turning, ignore)
	right front corner - turn left by x degrees, move as per normal
	right back corner - (if was moving forward, then move as per normal) (if was moving backward, move forward a bit, turn right, move as per normal)

	left front corner && left back corner - along boundary, move as per normal
	left front corner && right front corner - right at edge, turn 135 degrees and move as per normal
	left front corner && right back corner - turn right by x degrees, move as per normal
	left back corner && right front corner - turn right by x degrees, move as per normal
	left back corner && right back corner - go forward, move as per normal
	right front corner && right back corner - along boundary, move as per normal



	*/

	int atLeftFront = SensorValue [lineSensorLeftFront];
	int atLeftBack = SensorValue [lineSensorLeftBack];
	int atRightFront = SensorValue [lineSensorRightFront];
	int atRightBack = SensorValue [lineSensorRightBack];


}

void stopMovement() {
	motor [leftMotor] = 0;
	motor [rightMotor] = 0;
}

void moveForward() {
	motor [leftMotor] = 30;
	motor [rightMotor] = 30;
}

void moveBackward() {
	motor [leftMotor] = -30;
	motor [rightMotor] = -30;
}

void depositBall() {

}

task main()
{
	while (1==1) {
		if (detectBoundary()) {
			stopMovement();
		} else {
			moveForward();
		}
	}
}
